### ISSUE TITLE
3rd level menu links not being picked up

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSMap#70] opened 2015-04-23 14:54 UTC
See https://secure.helpscout.net/conversation/85892911/12302/

Screenshots of the menu:
![screen shot 2015-04-23 at 10 51 42 am](https://cloud.githubusercontent.com/assets/3868028/7299981/1dcfe5ec-e9a7-11e4-87c6-7d989c8c56ea.png)

And the XML sitemap:

![screen shot 2015-04-23 at 10 51 53 am](https://cloud.githubusercontent.com/assets/3868028/7299983/25a346a6-e9a7-11e4-8cda-17e98e121f60.png)

**Comment by htmgarcia** [comment] 2015-04-28 00:28
I can confirm the issue.

**Comment by dBarboni** [comment] 2015-05-22 19:06
This happened on my site as well, it was because of a menu item with the type Menu Item Alias. Changing it to the type External URL made the missing links show up in the XML.

**Comment by nicksavov** [comment] 2015-05-29 03:08
Thanks @dBarboni! Good find!

It worked for the user at https://www.alledia.com/forum/osmap/136/#966 too.

We'll still work on a fix for the Menu Item Alias though.

**Comment by htmgarcia** [comment] 2015-08-17 13:59
A new report: https://www.alledia.com/forum/osmap/218/

**Comment by JoomFX** [comment] 2015-08-24 10:00
I also have the same issue with OSMap and a "Menu Item Alias" menu item.

So I was wondering if there will be a fix soon or if I should rethink my menus and see if I can use "External Link" instead.

P.S.   @htmgarcia nice to see you here as well, Valentin ;)

**Comment by htmgarcia** [comment] 2015-08-24 18:05
Hi @JoomFX, is nice to see you here Ivo :)

Sorry about the issues you're having.

About the "Item Alias", the menu item linked to it should be crawled instead. Please verify in your end you include in the sitemap the menu that owns the original link.

**Comment by JoomFX** [comment] 2015-08-24 19:39
@htmgarcia Hey Valentin,

Thanks for the reply mate!

Well, here's my setup.... I have a main menu (1st level) item called "Support". It is a "Menu Item Alias".

Then I have a submenu item (2nd level) called "Support Forum" and it is pointing to the "EasyDiscuss" component.

The "Support" menu item is a "Menu Item Alias" pointing to the "Support Forum" submenu item:

![alt](http://i.imgur.com/ebopRBi.png)

With this setup, my XML sitemap does not include the URLs for "EasyDiscuss" (I have installed the OSMap/Xmap plugin from Stackideas for EasyDiscuss).

And as soon as I change the "Support" menu item to "External Link" or anything else different than "Menu Item Alias", my XML sitemap starts showing all EasyDiscuss URLs.

Let me know what you think about it and if there will be a fix for. I really do not want to change my menu structure :)

Thanks a lot Valentin!

**Comment by htmgarcia** [comment] 2015-08-28 12:58
Hi Ivo :) @JoomFX ,

If I understand, 
(1) the menu item for "Easy Discuss"
(2) the links to its topics are not being crawled?

In the case of (1) all the menu items from 1st and 2nd level should be crawled. It's the expected result. Please confirm which is your case.

In the case of (2) depends on the plugin, worth reporting the issue with the developer in case an update from them is required.

We appreciate your valuable feedback!

**Comment by JoomFX** [comment] 2015-08-29 16:53
Hey Valentin, @htmgarcia 

Well, we are not talking about crawling here (not directly).
The problem is that the URLs are not shown/included into the XML sitemap if the Menu Item is "Menu Item Alias". It will be best if I describe the problem with screenshots:

#### Main Menu Item is "Menu Item Alias"

![alt](http://i.imgur.com/s90cNdh.png)

Then the XML sitemap does not include the URLs of the submenu items (EasyDiscuss):

![alt](http://i.imgur.com/wnwx1WC.png)

#### Main Menu Items is anything else, except "Menu Item Alias". In this case it is "External Link"

![alt](http://i.imgur.com/hYvYgeL.png)

The XML sitemap works perfectly fine. All URLs are included as expected:

![alt](http://i.imgur.com/C0vDM4e.png)

Another interesting thing is that this problem is ONLY related to the XML sitemap. The HTML sitemap shows all URLs even if the Main Menu item is "Menu Item Alias".

It is obviously an issue with OSmap. Sorry for being so sure, but yeah, I think it is a bug in OSmap.

By the way I already discussed the issue with StackIdeas. You can find the discussion [here](http://stackideas.com/forums/osmap-plugin-for-easydiscuss), but I suppose you need a membership in order to view the replies. Anyway, the below screenshot shows their conclusion:

![alt](http://i.imgur.com/SbOMY9W.png)

Thanks a lot for helping me out with this Valentin :)

**Comment by JoomFX** [comment] 2015-08-29 17:17
Valentin, I just reproduced the issue with the default Joomla "Category Blog" menu item. So EasyDiscuss is no longer involved :)

Here are the steps to reproduce the issue:

1. Create a Main Menu Item of type "Menu Item Alias" and call it "Blog" (see step 3)
2. Create a submenu item of "Blog" of type "Category Blog" and call it "SubItem"
3. Go back to the "Blog" menu item and set it to link to "SubItem"
4. Open the XML sitemap and see that the article URLs are missing from the sitemap

I do understand that it is a strange configuration (Main Menu Item to link to a submenu item) but I really need it to be like this so I can manage the site URLs structure (without 3rd party extensions) and not to have duplicate content :)

**Comment by htmgarcia** [comment] 2015-09-01 03:28
Hi @JoomFX ,

Sorry for not being enough clear, by crawling I mean adding the urls in the sitemap.

I tested the configuration you suggested. In my case the menu item alias was added in the sitemap due the submenu item "Blog" (Category Blog) was located in second level.

The menu items type alias are not being added because they doesn't contain a working url, instead OSMap use the url from the working menu item, "Category blog" in this example.

In this sample menu:

> -- Blog (alias)
> ------ Subitem (category blog)

Only the second link will be added to the sitemap.

Hopes this clarification helps. If I'm missing any detail, please let me know.

**Comment by JoomFX** [comment] 2015-09-01 07:23
Hi @htmgarcia ,

Please watch the video below. It explains everything. Watch it in Fullscreen and HD :)

http://youtu.be/SPYRs-AJbow

I hope you can now see what I'm talking about and discuss it with the developers.
Let me know if you need anything else from me ;)

**Comment by htmgarcia** [comment] 2015-09-01 11:27
Thanks for sharing the video @JoomFX , that clarify your concern.
Clearly something is happening there, and we will fix as soon as possible :)

**Comment by JoomFX** [comment] 2015-09-01 12:25
@htmgarcia Thanks a lot Valentin :)

Could you please just update this issue once you fix the problem?

**Comment by htmgarcia** [comment] 2015-09-01 14:32
Sure thing, @JoomFX !

**Comment by nicksavov** [comment] 2015-11-05 21:33
Fixed with https://github.com/OSTraining/OSMap/issues/90#issuecomment-154198793 . Thanks everyone!

**Closed by nicksavov** 2015-11-05 21:33 UTC
Labels: bug, high
